
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=iterlstorage;AccountKey=C76kQZZEW56fRk4tN6ZhF0LLIoUnXexarOIve9m0BYJM0oT6swZL927ZKM7tVaIGbV4aKoIh6KmO+AStA680ig==;EndpointSuffix=core.windows.net
    container-name: iterlcontainer
    base-url: https://iterlstorage.blob.core.windows.net/iterlcontainer
    csv-file-directory: iterl-csv

server:
  port: 8080
spring:
  application:
    name: backendservice
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  data:
    mongodb:
      database: UserData
      uri: mongodb+srv://ITERLUser:BDITLconsultancy123@_mongodb._tcp.iterl-mongodb-cluster.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000